name: deploy-expiration
on:
    push:
        branches: 
            - master 
        paths: 
            - 'expiration/**'
jobs: 
    build:
        runs-on: ubuntu-latest 
        steps: 
            - uses: actions/checkout@v2 
            - run: cd expiration && docker build -t wiers/expiration .
            - 
              name: Login to Docker Hub
              uses: docker/login-action@v1
              with: 
                 username: ${{ secrets.DOCKER_USERNAME }}
                 password: ${{ secrets.DOCKERHUB_TOKEN }} 
            - run: docker push wiers/expiration
            - uses: digitalocean/action-doctl@v2
              with:
                token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
            - run: doctl kubernetes cluster kubeconfig save save k8s-1-23-9-do-0-ams3-1659093049827
            - run: kubectl rollout restart deployment expiration-depl