name: deploy-auth
on:
    push:
        branches: 
            - master 
        paths: 
            - 'auth/**'
jobs: 
    build:
        runs-on: ubuntu-latest 
        steps: 
            - uses: actions/checkout@v2 
            - run: cd auth && docker build -t wiers/auth .
            - run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
            - run: docker push wiers/auth
            - uses: digitalocean/action-doctl@v2
              with:
                token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
            - run: doctl kubernetes cluster kubeconfig save ticketing
            - run: kubectl rollout restart deployment auth-depl
            - run: docker logout
