name: deploy-manifests

on:
    push:
        branches: 
            - master 
        paths: 
            - 'infra/**'
            
jobs: 
    build:
        runs-on: ubuntu-latest 
        steps: 
           - uses: actions/checkout@v2 
           - uses: digitalocean/action-doctl@v2
             with:
               token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
           - run: doctl kubernetes cluster kubeconfig save k8s-1-23-9-do-0-ams3-1659093049827
           - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
